version: '3.8'

services:
  web-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - "postgre_db"
  postgre_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "diplom_backend"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: "5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", pg_isready -U postgres -d diplom_backend]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  redis:
    image: redis
    ports:
      - "6379:6379"