version: '3.9'

services:
  web-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - "postgre_db"
  postgre_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "diplom_backend"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", pg_isready -U admin -d new_db]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s