# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/api/v1

# получение категорий
GET {{baseUrl}}/categories
Content-Type: application/json

###


# добавление категорий
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "name": "electronics"
}

###

# получение магазинов
GET {{baseUrl}}/shops
Content-Type: application/json

###


# добавление магазинов
POST {{baseUrl}}/shops
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "name": "cool shop",
  "url": "http://check.com",
  "status": "active"
}

###


# изменение магазина
PATCH {{baseUrl}}/shops
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "id": 27,
  "name": "coouul shop",
  "url": "http://check.ru",
  "user": 13
}

###

# создание пользователя
POST {{baseUrl}}/user/register
Content-Type: application/json

{
  "username": "vers",
  "first_name": "CLOSED",
  "last_name":"check",
  "email":"agh7gehf9@gmail.com",
  "password":"che11ck",
  "age": 67,
  "company":"check",
  "position": 7678
}

###

# вход
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "email":"agh7gehf9@gmail.com",
  "password":"che11ck"
}

###

#получение данных аккаунта
GET {{baseUrl}}/user/detail_account
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

###

#редактирование данных аккаунта
POST {{baseUrl}}/user/detail_account
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "email":"agh7gehf9@gmail.com",
  "age":"55"
}
###

#получение контактов
GET {{baseUrl}}/user/contacts
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062
###

#редактирование контакта
PATCH {{baseUrl}}/user/contacts
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "phone":"+34234234",
  "id": 14
}

###

#удаление контакта
DELETE {{baseUrl}}/user/contacts
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "id": 13
}
###

#Добавление контакта
POST {{baseUrl}}/user/contacts
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "city": "uoooooo",
  "house": "hhgerg",
  "street": "qweqwed",
  "structure": "12123",
  "building": "2424",
  "apartment": "46623",
  "phone":"+34234234"
}

###

#добавление инфо товара
POST {{baseUrl}}/product/info
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
"model": "Siemens",
"info_id": 4,
"product": 1,
"shop": 27,
"quantity": 6576,
"price": 98878,
"price_rrc": 80000
}
###

#получение инфо о товаре
GET {{baseUrl}}/product/info
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "product_id": 1,
  "shop_id": 27
}

###

#обновление инфо товара
PATCH {{baseUrl}}/product/info
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "product_info_id": 63,
  "shop": 27,
  "product": 1,
  "info_id": 6
}

###

#удаление товара
DELETE {{baseUrl}}/product/info
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "id": 64,
  "shop": 27
}

###
# добавление товара в корзину
POST {{baseUrl}}/basket/info
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{

"product_info": 63, 
"quantity": 44

}

###

# просмотр корзины
GET {{baseUrl}}/basket/info
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

###
# редактирование корзины/подтверждение заказа
PATCH  {{baseUrl}}/basket/info
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{

"id": 25, 
"quantity": 4444

}

###
# удаление товара из корзины
DELETE  {{baseUrl}}/basket/info
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{

"id": 46

}

###