# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/api/v1

# получение категорий
GET {{baseUrl}}/categories
Content-Type: application/json

###


# добавление категорий
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "name": "tank"
}

###

# получение товара
GET {{baseUrl}}/products
Content-Type: application/json

###


# добавление товара
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "category_id": 1,
  "name": "Acer"
}

###

# получение магазинов
GET {{baseUrl}}/shops
Content-Type: application/json

###


# добавление магазинов
POST {{baseUrl}}/shops
Content-Type: application/json
# Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062
Authorization: Token bd14074aefa5730334c8b55c5e4996aec01ed07c


{
  "name": "cured66eee",
  "url": "http://iuitm.com"
}

###


# изменение магазина
PATCH {{baseUrl}}/shops
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "id": 27,
  "name": "гггuulнн sho77p",
  "url": "http://check.ru",
  "status": "closed"
}

###

# создание пользователя
POST {{baseUrl}}/user/register
Content-Type: application/json

{
  "username": "vwwwers",
  "first_name": "CLOSED",
  "last_name":"check",
  "email":"agh7gerrr9@gmail.com",
  "password":"che11ck",
  "age": 67,
  "company":"check",
  "position": 7678
}

###

# вход
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "email":"agh7gehuuuf9@gmail.com",
  "password":"che11ck"
}

###

#получение данных аккаунта
GET {{baseUrl}}/user/detail_account
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

###

#редактирование данных аккаунта
POST {{baseUrl}}/user/detail_account
Content-Type: application/json
# Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062
Authorization: Token bd14074aefa5730334c8b55c5e4996aec01ed07c

{
  "username": "stars",
  "email":"agh7gehuuuf9@gmail.com",
  "age":"55"
}
###

#получение контактов
GET {{baseUrl}}/user/contacts
Content-Type: application/json
# Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062
Authorization: Token bd14074aefa5730334c8b55c5e4996aec01ed07c

{
  "id": 18
}


###

#редактирование контакта
PATCH {{baseUrl}}/user/contacts
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "phone":"+34234234",
  "id": 14
}

###

#удаление контакта
DELETE {{baseUrl}}/user/contacts
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "id": 13
}
###

#Добавление контакта
POST {{baseUrl}}/user/contacts
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "city": "uoooooo",
  "house": "hhgerg",
  "street": "qweqwed",
  "structure": "12123",
  "building": "2424",
  "apartment": "46623",
  "phone":"+34234234"
}

###

#добавление инфо товара
POST {{baseUrl}}/product/info
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
"model": "Vodka",
"info_id": 66,
"product": 1,
"shop": 27,
"quantity": 6576,
"price": 98878,
"price_rrc": 80000,
"product_parameters": [{"weight": 34, "height": 777}]
}
###

#получение инфо о товаре
GET {{baseUrl}}/product/info
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "product_id": 1,
  "shop_id": 27
}

###

#обновление инфо товара
PATCH {{baseUrl}}/product/info
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "product_info_id": 70,
  "shop": 27,
  "product": 1,
  "info_id": 99,
  "product_parameters": [{"weight": 1010, "height": 6666}]
}

###

#удаление товара
DELETE {{baseUrl}}/product/info
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{
  "id": 65,
  "shop": 27
}

###
# добавление товара в корзину
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{

"product_info": 63, 
"quantity": 44

}

###

# просмотр товаров в корзине или для поставщика
GET {{baseUrl}}/orders
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

###
# редактирование корзины/подтверждение заказа
PATCH  {{baseUrl}}/orders
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{

"id": 50, 
"contact": 18,
"product_info": 63

}

###
# удаление товара из корзины
DELETE  {{baseUrl}}/orders
Content-Type: application/json
Authorization: Token d1e3abe426ee0c31d674f61d9af750913358f062

{

"id": 48

}

###